# Generated by Django 3.2.4 on 2021-09-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210903_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
