# Generated by Django 3.2.4 on 2021-09-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_purchase_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='image',
        ),
        migrations.AddField(
            model_name='subscription',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
