# Generated by Django 3.2.7 on 2021-09-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Purchase',
            new_name='purchase',
        ),
    ]
